/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ILeafWalletRegistryCore,
  ILeafWalletRegistryCoreInterface,
} from "../../contracts/ILeafWalletRegistryCore";

const _abi = [
  {
    inputs: [],
    name: "getDeviceOwner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getRelatedDevices",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "isSenderRegistered",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ILeafWalletRegistryCore__factory {
  static readonly abi = _abi;
  static createInterface(): ILeafWalletRegistryCoreInterface {
    return new utils.Interface(_abi) as ILeafWalletRegistryCoreInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILeafWalletRegistryCore {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ILeafWalletRegistryCore;
  }
}
