/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ILeafWalletRegistryActivate,
  ILeafWalletRegistryActivateInterface,
} from "../../contracts/ILeafWalletRegistryActivate";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "assignee",
        type: "address",
      },
    ],
    name: "assignActivatableAddressToSender",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getActivationCodeOfSender",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getDeviceOwner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getRelatedDevices",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "isSenderRegistered",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ILeafWalletRegistryActivate__factory {
  static readonly abi = _abi;
  static createInterface(): ILeafWalletRegistryActivateInterface {
    return new utils.Interface(_abi) as ILeafWalletRegistryActivateInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILeafWalletRegistryActivate {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ILeafWalletRegistryActivate;
  }
}
