/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { InitFacet__factory } from "./InitFacet__factory";
export { LibPeoplesPlatform__factory } from "./LibPeoplesPlatform__factory";
export { PeoplesPlatformFacet__factory } from "./PeoplesPlatformFacet__factory";
