/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type {
  LeafWalletRegistryCore,
  LeafWalletRegistryCoreInterface,
} from "../../contracts/LeafWalletRegistryCore";

const _abi = [
  {
    inputs: [],
    name: "getDeviceOwner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getRelatedDevices",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "isSenderRegistered",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608080604052346100165761021c908161001c8239f35b600080fdfe6080604090808252600436101561001557600080fd5b600090813560e01c9081633aafa38814610194575080639b8ae3751461013f5763e0f64efc1461004457600080fd5b3461013c578060031936011261013c573381526020907f83ed3ba29c1d52058c877df3ebd264cf957c42ef7764387349be0ccf6df0b63c825282812091835191828285549182815201908195835283832090835b8582821061011f5750505050839003601f01601f191683019467ffffffffffffffff86118487101761010b5785815282865292518583018190528594938501939290915b8281106100eb57505050500390f35b83516001600160a01b0316855286955093810193928101926001016100dc565b634e487b7160e01b82526041600452602482fd5b83546001600160a01b031685529093019260019283019201610098565b80fd5b5090346101905781600319360112610190573382527f83ed3ba29c1d52058c877df3ebd264cf957c42ef7764387349be0ccf6df0b63b6020908152918190205490516001600160a01b039091168152f35b5080fd5b905082346101e257826003193601126101e2573383527f83ed3ba29c1d52058c877df3ebd264cf957c42ef7764387349be0ccf6df0b63b60209081529220546001600160a01b031615158152f35b8280fdfea26469706673582212202a905a841c58b9c1f23fdbe713f852980fc597046189fd10a3ed687cf6fc4ed364736f6c63430008120033";

type LeafWalletRegistryCoreConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LeafWalletRegistryCoreConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class LeafWalletRegistryCore__factory extends ContractFactory {
  constructor(...args: LeafWalletRegistryCoreConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<LeafWalletRegistryCore> {
    return super.deploy(overrides || {}) as Promise<LeafWalletRegistryCore>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): LeafWalletRegistryCore {
    return super.attach(address) as LeafWalletRegistryCore;
  }
  override connect(signer: Signer): LeafWalletRegistryCore__factory {
    return super.connect(signer) as LeafWalletRegistryCore__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LeafWalletRegistryCoreInterface {
    return new utils.Interface(_abi) as LeafWalletRegistryCoreInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LeafWalletRegistryCore {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as LeafWalletRegistryCore;
  }
}
