/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { InitFacet } from "./InitFacet";
export type { LibPeoplesPlatform } from "./LibPeoplesPlatform";
export type { PeoplesPlatformFacet } from "./PeoplesPlatformFacet";
