/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface SusuwatariLeafWalletFacetInterface extends utils.Interface {
  functions: {
    "assignActivatableAddressToSender(address)": FunctionFragment;
    "getActivationCodeOfSender()": FunctionFragment;
    "getDeviceOwner()": FunctionFragment;
    "getRelatedDevices()": FunctionFragment;
    "isSenderRegistered()": FunctionFragment;
    "registerAndAssignMe(uint8)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "assignActivatableAddressToSender"
      | "getActivationCodeOfSender"
      | "getDeviceOwner"
      | "getRelatedDevices"
      | "isSenderRegistered"
      | "registerAndAssignMe"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "assignActivatableAddressToSender",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getActivationCodeOfSender",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDeviceOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRelatedDevices",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isSenderRegistered",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerAndAssignMe",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "assignActivatableAddressToSender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActivationCodeOfSender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeviceOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRelatedDevices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSenderRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAndAssignMe",
    data: BytesLike
  ): Result;

  events: {
    "AssignActivatableAddressToSenderReturn(uint256)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "AssignActivatableAddressToSenderReturn"
  ): EventFragment;
}

export interface AssignActivatableAddressToSenderReturnEventObject {
  arg0: BigNumber;
}
export type AssignActivatableAddressToSenderReturnEvent = TypedEvent<
  [BigNumber],
  AssignActivatableAddressToSenderReturnEventObject
>;

export type AssignActivatableAddressToSenderReturnEventFilter =
  TypedEventFilter<AssignActivatableAddressToSenderReturnEvent>;

export interface SusuwatariLeafWalletFacet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SusuwatariLeafWalletFacetInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    assignActivatableAddressToSender(
      assignee: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getActivationCodeOfSender(overrides?: CallOverrides): Promise<[BigNumber]>;

    getDeviceOwner(overrides?: CallOverrides): Promise<[string]>;

    getRelatedDevices(overrides?: CallOverrides): Promise<[string[]]>;

    isSenderRegistered(overrides?: CallOverrides): Promise<[boolean]>;

    registerAndAssignMe(
      team: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  assignActivatableAddressToSender(
    assignee: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getActivationCodeOfSender(overrides?: CallOverrides): Promise<BigNumber>;

  getDeviceOwner(overrides?: CallOverrides): Promise<string>;

  getRelatedDevices(overrides?: CallOverrides): Promise<string[]>;

  isSenderRegistered(overrides?: CallOverrides): Promise<boolean>;

  registerAndAssignMe(
    team: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    assignActivatableAddressToSender(
      assignee: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    getActivationCodeOfSender(overrides?: CallOverrides): Promise<BigNumber>;

    getDeviceOwner(overrides?: CallOverrides): Promise<string>;

    getRelatedDevices(overrides?: CallOverrides): Promise<string[]>;

    isSenderRegistered(overrides?: CallOverrides): Promise<boolean>;

    registerAndAssignMe(
      team: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AssignActivatableAddressToSenderReturn(uint256)"(
      arg0?: null
    ): AssignActivatableAddressToSenderReturnEventFilter;
    AssignActivatableAddressToSenderReturn(
      arg0?: null
    ): AssignActivatableAddressToSenderReturnEventFilter;
  };

  estimateGas: {
    assignActivatableAddressToSender(
      assignee: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getActivationCodeOfSender(overrides?: CallOverrides): Promise<BigNumber>;

    getDeviceOwner(overrides?: CallOverrides): Promise<BigNumber>;

    getRelatedDevices(overrides?: CallOverrides): Promise<BigNumber>;

    isSenderRegistered(overrides?: CallOverrides): Promise<BigNumber>;

    registerAndAssignMe(
      team: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    assignActivatableAddressToSender(
      assignee: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getActivationCodeOfSender(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDeviceOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRelatedDevices(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isSenderRegistered(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registerAndAssignMe(
      team: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
