/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  LeafWalletRegistryBasic,
  LeafWalletRegistryBasicInterface,
} from "../../../contracts/LeafWalletRegistryBase.sol/LeafWalletRegistryBasic";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "assignee",
        type: "address",
      },
    ],
    name: "assignAddressToSender",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getDeviceOwner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getRelatedDevices",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "isSenderRegistered",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60808060405234610016576103a6908161001c8239f35b600080fdfe60806040908082526004918236101561001757600080fd5b600091823560e01c9081633aafa388146103225750806356a593e3146101a25780639b8ae375146101525763e0f64efc1461005157600080fd5b3461014e578160031936011261014e573360009081527f83ed3ba29c1d52058c877df3ebd264cf957c42ef7764387349be0ccf6df0b63c6020526040902091815190819284548084526020809401908196845284842090845b868282106101315750505050849003601f01601f191684019567ffffffffffffffff87118588101761011e575085815282865292518583018190528594938501939290915b8281106100fe57505050500390f35b83516001600160a01b0316855286955093810193928101926001016100ef565b634e487b7160e01b835260419052602482fd5b83546001600160a01b0316855290930192600192830192016100aa565b5080fd5b503461014e578160031936011261014e573382527f83ed3ba29c1d52058c877df3ebd264cf957c42ef7764387349be0ccf6df0b63b6020908152918190205490516001600160a01b039091168152f35b5082903461031e576020918260031936011261031a576001600160a01b03813581811694919290859003610316578486527f83ed3ba29c1d52058c877df3ebd264cf957c42ef7764387349be0ccf6df0b63b92838352808588205416801590811561030c575b50156102ca57858752838352848720541615610222578580f35b3360009081527f83ed3ba29c1d52058c877df3ebd264cf957c42ef7764387349be0ccf6df0b63c60205260409020805491680100000000000000008310156102b757600183018083558310156102a4575086528186200180546001600160a01b0319908116861790915593855252822080549091163317905581808080808580f35b634e487b7160e01b885260329052602487fd5b634e487b7160e01b885260419052602487fd5b5060649184519162461bcd60e51b8352820152601960248201527f44657669636520616c72656164792072656769737465726564000000000000006044820152fd5b9050331488610208565b8580fd5b8380fd5b8280fd5b9190503461031e578260031936011261031e573383527f83ed3ba29c1d52058c877df3ebd264cf957c42ef7764387349be0ccf6df0b63b60209081529220546001600160a01b031615158152f3fea264697066735822122001f3a865b2068cf8f1e4def0a4538c9068507ebcfa53fe591203ab6e7cf0dc2364736f6c63430008120033";

type LeafWalletRegistryBasicConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LeafWalletRegistryBasicConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class LeafWalletRegistryBasic__factory extends ContractFactory {
  constructor(...args: LeafWalletRegistryBasicConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<LeafWalletRegistryBasic> {
    return super.deploy(overrides || {}) as Promise<LeafWalletRegistryBasic>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): LeafWalletRegistryBasic {
    return super.attach(address) as LeafWalletRegistryBasic;
  }
  override connect(signer: Signer): LeafWalletRegistryBasic__factory {
    return super.connect(signer) as LeafWalletRegistryBasic__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LeafWalletRegistryBasicInterface {
    return new utils.Interface(_abi) as LeafWalletRegistryBasicInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LeafWalletRegistryBasic {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as LeafWalletRegistryBasic;
  }
}
