/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contracts from "./contracts";
export type { contracts };
import type * as hardhatDeploy from "./hardhat-deploy";
export type { hardhatDeploy };
export * as factories from "./factories";
export type { InitFacet } from "./contracts/InitFacet";
export { InitFacet__factory } from "./factories/contracts/InitFacet__factory";
export type { LibPeoplesPlatform } from "./contracts/LibPeoplesPlatform";
export { LibPeoplesPlatform__factory } from "./factories/contracts/LibPeoplesPlatform__factory";
export type { PeoplesPlatformFacet } from "./contracts/PeoplesPlatformFacet";
export { PeoplesPlatformFacet__factory } from "./factories/contracts/PeoplesPlatformFacet__factory";
export type { IDiamondCut } from "./hardhat-deploy/solc_0.8/diamond/interfaces/IDiamondCut";
export { IDiamondCut__factory } from "./factories/hardhat-deploy/solc_0.8/diamond/interfaces/IDiamondCut__factory";
export type { IDiamondLoupe } from "./hardhat-deploy/solc_0.8/diamond/interfaces/IDiamondLoupe";
export { IDiamondLoupe__factory } from "./factories/hardhat-deploy/solc_0.8/diamond/interfaces/IDiamondLoupe__factory";
export type { LibDiamond } from "./hardhat-deploy/solc_0.8/diamond/libraries/LibDiamond";
export { LibDiamond__factory } from "./factories/hardhat-deploy/solc_0.8/diamond/libraries/LibDiamond__factory";
